project:
  type: website
  output-dir: "docs"

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Anaïs Léger"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Porfolio"
        file: portfolio.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AnaisLeger23
      - icon: linkedin
        href: https://www.linkedin.com/in/anaisleger/
      - icon: book
        href: https://scholar.google.com/citations?hl=fr&tzom=-60&user=3e7GAhMAAAAJ&view_op=list_works
format:
  html:
    theme:
      - minty
    css: styles.css

editor: visual

